spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: ${PORT:8080}

app:
  auth:
    session-ttl-hours: 24
  link:
    ttl-hours: 24
